
package artifact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebService", targetNamespace = "http://webpackage/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://webpackage/", className = "artifact.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://webpackage/", className = "artifact.GetNameResponse")
    public String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subscribe", targetNamespace = "http://webpackage/", className = "artifact.Subscribe")
    @ResponseWrapper(localName = "subscribeResponse", targetNamespace = "http://webpackage/", className = "artifact.SubscribeResponse")
    public String subscribe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unsubscribe", targetNamespace = "http://webpackage/", className = "artifact.Unsubscribe")
    @ResponseWrapper(localName = "unsubscribeResponse", targetNamespace = "http://webpackage/", className = "artifact.UnsubscribeResponse")
    public String unsubscribe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSubscribers", targetNamespace = "http://webpackage/", className = "artifact.ListSubscribers")
    @ResponseWrapper(localName = "listSubscribersResponse", targetNamespace = "http://webpackage/", className = "artifact.ListSubscribersResponse")
    public String listSubscribers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
